apiVersion: v1
kind: Service
metadata:
  name: flask-web-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
#    nodePort: 32123
    name: http
  selector:
    app: flask-web-app
    version: v1