version: '3.8'

services:
  mysql_db:
    image: ivywr/p4-wscb:wscb_db_image
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "wscb_db"
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  url_shortener_service:
    image: ivywr/p4-wscb:url_shorten_image
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:12345678@mysql_db:3306/wscb_db"
    ports:
      - "5001:5001"
    depends_on:
      - mysql_db

  auth_service:
    image: ivywr/p4-wscb:auth_image
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:12345678@mysql_db:3306/wscb_db"
    ports:
      - "5002:5002"
    depends_on:
      - mysql_db

  nginx:
    image: ivywr/p4-wscb:nginx_image
    ports:
      - "5003:80"
    depends_on:
      - url_shortener_service
      - auth_service

volumes:
  db-data:
