version: '3.8'

services:
  mysql-db:
    image: ivywr/p4-wscb:wscb_db_image
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "wscb_db"
    ports:
      - "3307:3306"
    networks:
      - wscb_network
    volumes:
      - db-data:/var/lib/mysql

  url-shorten-service:
    image: ivywr/p4-wscb:url_shorten_image
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:12345678@mysql-db:3306/wscb_db"
    ports:
      - "5001:5001"
    networks:
      - wscb_network
    depends_on:
      - mysql-db

  auth-service:
    image: ivywr/p4-wscb:auth_image
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:12345678@mysql-db:3306/wscb_db"
    ports:
      - "5002:5002"
    networks:
      - wscb_network
    depends_on:
      - mysql-db

  nginx:
    image: ivywr/p4-wscb:nginx_image
    ports:
      - "5003:80"
    networks:
      - wscb_network
    depends_on:
      - url-shorten-service
      - auth-service

networks:
  wscb_network:

volumes:
  db-data:
