---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-app
  labels:
    app: flask-web-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-web-app
      version: v1
  template:
    metadata:
      labels:
        app: flask-web-app
        version: v1
    spec:
      containers:
      - name: flask-web-app
        image: registry.cn-hangzhou.aliyuncs.com/csugis/我的仓库:版本号
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: flask-web-app-service
spec:
  type: NodePort
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
    nodePort: 32510
    name: http
  selector:
    app: flask-web-app
    version: v1
