apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  db-user: cm9vdA==  # base64 encoded 'root'
  db-password: MTIzNDU2Nzg=  # base64 encoded '12345678'

